# Generated by Django 5.1.3 on 2024-12-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_language_type_work_type_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_users', to='api.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_users', to='api.language'),
        ),
        migrations.AlterField(
            model_name='work',
            name='difficulty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.type'),
        ),
    ]
